### ISSUE TITLE
Feature request: support for domain users

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-mssql#29]
Hello,

when I try to use `Invoke-IcingaCheckMSSQLHealth` with a domain user (parameter `SqlUsername`) the connect fails. On the db-side the login attempt is shown as if a local sql user was used. Is there already support for domain users?

**Comment by LordHepipud** [comment]
Thank you for the request. As far as my research went, it is not possible to login with domain specific users into the database, without using the integrated security option. I will have to dig deeper into this, but for that reason the integrated security was used which makes use of the current user context executing the plugin.

**Comment by LordHepipud** [comment]
After some more research, it seems this is only possible by using `IntegratedSecurity` and the domain user in question is opening the connection, either with an active PowerShell for the user or an active windows session.

If there is anyone knowing a different way of providing AD credentials to the SQL connection string, please hit me up and I will implement that.
