### ISSUE TITLE
How to import the director files?

### ISSUE THREAD

**Issue by ronnybremer** [Icinga/icinga-powershell-mssql#41]
I am trying to integrate the module into Icinga2 with the Director module installed. I can see the JSON files in here, but how can I import them into the director?

**Comment by RincewindsHat** [comment]
[Via the Basket Upload functionality](http://YOUR-SERVER/icingaweb2/director/basket/upload)

**Comment by ronnybremer** [comment]
Ahh, that makes a lot of sense. I haven't used them in the past. Thank you!
